# Generated by Django 4.2.19 on 2025-02-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
