# Generated by Django 4.2.19 on 2025-03-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoUser',
        ),
    ]
