# Generated by Django 4.2.19 on 2025-02-23 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Todo", "0002_alter_todo_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "Todo"},
        ),
    ]
